"""auto_fix_schema_mismatches

Revision ID: 2a1aaca28cd8
Revises: c1d2e3f4g5h6
Create Date: 2026-06-25 12:25:47.077450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1aaca28cd8'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cumulative_phase_scores', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('cumulative_phase_scores_team_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('leaderboard_team_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['external_api_id'])

    with op.batch_alter_table('model_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('UPLOADED', 'TESTING', 'EVALUATED', 'FAILED', name='model_status_enum', create_constraint=True), nullable=False))
        batch_op.drop_index(batch_op.f('ix_model_submissions_team_active'))

    with op.batch_alter_table('player_actuals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('player_actuals_actual_result_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'actual_results', ['actual_result_id'], ['id'])

    with op.batch_alter_table('player_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.String(length=255), nullable=True))
        batch_op.alter_column('player_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('player_predictions_prediction_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'predictions', ['prediction_id'], ['id'])

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('both_teams_to_score_prediction', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('first_goal_team_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clean_sheet_predictions', sa.JSON(), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('match_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('presentation_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('judge_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('presentation_criteria_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('max_marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('round_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('raw_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('presentation_evaluations_team_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_presentation_evaluations_team_id'))
        batch_op.create_index('ix_presentation_evaluations_team_id', ['team_id'], unique=False)
        batch_op.create_unique_constraint('uq_team_presentation_round', ['team_id', 'round_id'])
        batch_op.drop_constraint(batch_op.f('presentation_evaluations_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'presentation_rounds', ['round_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('winner_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('scoreline_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('probability_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('player_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_goals_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('btts_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('first_team_to_score_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('clean_sheet_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probability_high_threshold', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('probability_high_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('probability_medium_threshold', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('probability_medium_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_goals_points_exact', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_goals_points_wrong', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('btts_points_correct', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('btts_points_incorrect', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_team_to_score_points_correct', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_team_to_score_points_incorrect', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('clean_sheet_points_correct', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('clean_sheet_points_incorrect', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('presentation_criteria', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('presentation_judge_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_constraint(batch_op.f('team_members_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('role')
        batch_op.drop_column('email')
        batch_op.drop_column('contact')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('team_leader_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('teams_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_teams_name_normalized'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_teams_team_id'), type_='unique')

    with op.batch_alter_table('technical_evaluations', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('technical_evaluations_team_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_evaluations', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('technical_evaluations_team_id_fkey'), 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_teams_team_id'), ['team_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_teams_name_normalized'), ['name_normalized'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('teams_code_key'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('team_leader_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_members_team_id_fkey'), 'teams', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.drop_column('presentation_judge_count')
        batch_op.drop_column('presentation_criteria')
        batch_op.drop_column('clean_sheet_points_incorrect')
        batch_op.drop_column('clean_sheet_points_correct')
        batch_op.drop_column('first_team_to_score_points_incorrect')
        batch_op.drop_column('first_team_to_score_points_correct')
        batch_op.drop_column('btts_points_incorrect')
        batch_op.drop_column('btts_points_correct')
        batch_op.drop_column('total_goals_points_wrong')
        batch_op.drop_column('total_goals_points_exact')
        batch_op.drop_column('probability_medium_points')
        batch_op.drop_column('probability_medium_threshold')
        batch_op.drop_column('probability_high_points')
        batch_op.drop_column('probability_high_threshold')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('clean_sheet_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('first_team_to_score_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('btts_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_goals_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('player_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('probability_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('scoreline_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('winner_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('presentation_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('presentation_evaluations_team_id_fkey'), 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_constraint('uq_team_presentation_round', type_='unique')
        batch_op.drop_index('ix_presentation_evaluations_team_id')
        batch_op.create_index(batch_op.f('ix_presentation_evaluations_team_id'), ['team_id'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('presentation_evaluations_team_id_key'), ['team_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('raw_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('round_id')
        batch_op.drop_column('max_marks')
        batch_op.drop_column('presentation_criteria_config')
        batch_op.drop_column('judge_scores')
        batch_op.drop_column('judge_count')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('match_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('clean_sheet_predictions')
        batch_op.drop_column('first_goal_team_probability')
        batch_op.drop_column('both_teams_to_score_prediction')

    with op.batch_alter_table('player_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_predictions_prediction_id_fkey'), 'predictions', ['prediction_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('player_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('team')

    with op.batch_alter_table('player_actuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_actuals_actual_result_id_fkey'), 'actual_results', ['actual_result_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('model_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_submissions_team_active'), ['team_id', 'is_active'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('notes')
        batch_op.drop_column('description')
        batch_op.drop_column('model_type')
        batch_op.drop_column('version')
        batch_op.drop_column('model_name')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('leaderboard_team_id_fkey'), 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('cumulative_phase_scores', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('cumulative_phase_scores_team_id_fkey'), 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###

