"""Float scoring configs

Revision ID: 5e6f7bb94e76
Revises: 7e8eecbac308
Create Date: 2026-07-01 12:21:16.957809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e6f7bb94e76'
down_revision: Union[str, Sequence[str], None] = '7e8eecbac308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_results', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'matches', ['match_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('clean_sheet_predictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('winner_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('scoreline_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('probability_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('player_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.alter_column('winner_points_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('winner_points_incorrect',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('scoreline_points_exact',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('10'))
        batch_op.alter_column('scoreline_points_margin',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('scoreline_points_incorrect',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('probability_points_pass',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('probability_points_fail',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('probability_high_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('probability_medium_points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('player_points_exact',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('player_points_close',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('player_points_wrong',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_goals_points_exact',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('total_goals_points_wrong',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('btts_points_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('btts_points_incorrect',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('first_team_to_score_points_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('first_team_to_score_points_incorrect',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('clean_sheet_points_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('clean_sheet_points_incorrect',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('max_base_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('25'))
        batch_op.alter_column('technical_max_per_category',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('technical_max_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('20'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_configs', schema=None) as batch_op:
        batch_op.alter_column('technical_max_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('20'))
        batch_op.alter_column('technical_max_per_category',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('max_base_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('25'))
        batch_op.alter_column('clean_sheet_points_incorrect',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('clean_sheet_points_correct',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('first_team_to_score_points_incorrect',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('first_team_to_score_points_correct',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('btts_points_incorrect',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('btts_points_correct',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('total_goals_points_wrong',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_goals_points_exact',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('player_points_wrong',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('player_points_close',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('player_points_exact',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('probability_medium_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('probability_high_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('probability_points_fail',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('probability_points_pass',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('scoreline_points_incorrect',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('scoreline_points_margin',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('scoreline_points_exact',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('10'))
        batch_op.alter_column('winner_points_incorrect',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('winner_points_correct',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('5'))

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('player_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('probability_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('scoreline_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('winner_points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('clean_sheet_predictions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('actual_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
