"""drop_legacy_scoring_fields

Revision ID: cd8aa3396ca3
Revises: 3511674ec231
Create Date: 2026-07-03 05:58:21.718032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8aa3396ca3'
down_revision: Union[str, Sequence[str], None] = '3511674ec231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('goal_difference_points')
        batch_op.drop_column('first_team_to_score_probability_points')
        batch_op.drop_column('winner_confidence_points')
        batch_op.drop_column('btts_probability_points')
        batch_op.drop_column('goal_scorer_points')
        batch_op.drop_column('exact_scoreline_points')
        batch_op.drop_column('winner_prediction_points')
        batch_op.drop_column('one_team_score_points')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_team_score_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winner_prediction_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exact_scoreline_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goal_scorer_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('btts_probability_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winner_confidence_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_team_to_score_probability_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goal_difference_points', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
